<a href="https://colab.research.google.com/github/Roshan1115/Artificial_Neural_Network/blob/main/Neural_Network_Playlist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.random.seed(0)

# X = [[1, 2, 3, 2.5],
#      [2.0, 5.0, -1.0, 2.0],
#      [-1.5, 2.7, 3.3, -0.8]]


#class for feedforward without activation function

class layer_dense:
  def __init__(self, n_input, n_neuron):  #neurons of hidden layer
    self.weights = 0.10 * np.random.randn(n_input, n_neuron)
    self.bias = np.zeros((1,n_neuron))
  
  def forward(self, input):
    self.output = np.dot(input, self.weights) + self.bias





In [ ]:
# Activation Functions

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)


class Activation_SoftMax:
  def forward(self, inputs):
    self.exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    self.probability = self.exp_values / np.sum(self.exp_values, axis=1, keepdims=True)
    self.output = self.probability


In [ ]:
# loss function

class Loss:
  def calculate(self, output, y):
    sample_loss = self.forward(output, y)
    data_loss = np.mean(sample_loss)
    return sample_loss



class Loss_CategoricalCrossEntropy(Loss):
  def forward(self, y_pred, y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

    if len(y_true.shape) == 1:
      correct_confidence = y_pred_clipped[range(samples), y_true]

    elif len(y_true.shape) == 2:
      correct_confidence = np.sum(y_pred_clipped * y_true, axis = 1)
      
    negative_log_likelihood = - np.log(correct_confidence)
    return negative_log_likelihood




In [ ]:
# spiral data creation

def create_data(points, classes):
  N = points
  D = 2
  K = classes
  X = np.zeros((N*K,D)) 
  y = np.zeros(N*K, dtype='uint8') 
  for j in range(K):
    ix = range(N*j,N*(j+1))
    r = np.linspace(0.0,1,N) # radius
    t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2 # theta
    X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
    y[ix] = j
  return X,y


import matplotlib.pyplot as plt

X, y = create_data(100,3)

# plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.Spectral)
# plt.show()



dense1 = layer_dense(2, 3)
activation1 = Activation_ReLU()

dense2 = layer_dense(3, 3)
activation2 = Activation_SoftMax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)


print("Predicted values")
print(activation2.output[:5])

print("\nActual class of each point")
print(y)

loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)

print("\nLoss is ")
print(loss[:5])


Predicted values
[[0.33333333 0.33333333 0.33333333]
 [0.33335607 0.33332304 0.33332089]
 [0.33337862 0.33331283 0.33330855]
 [0.33340383 0.33330133 0.33329484]
 [0.33342841 0.33329014 0.33328145]]

Actual class of each point
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2]

Loss is 
[1.09861229 1.09854408 1.09847643 1.09840082 1.0983271 ]
